### ISSUE TITLE
Hardware Shopping List

### ISSUE THREAD

**Issue by twkm** [PumpInteractive/PumpFoos#55]
Goal for the first version of hardware is to get some buttons working as keyboard inputs. Future versions could incorporate LEDs or other such fanciness.
## Buttons
- [ ] 15x [Yellow Arcade Buttons](https://www.sparkfun.com/products/9338)
- [ ] 15x [Black Arcade Buttons](https://www.sparkfun.com/products/9339)

Will need 26 buttons for players (13 a side), but get a few extra for backup/other uses.
## Controller and Components
- [ ] [Teensy 3.2](https://www.sparkfun.com/products/13736)
  - Teensy can emulate a keyboard, use the arcade buttons as inputs. Front end could then listen to fire events via JS
  - [ ] 5-8x [Shift Register](https://www.sparkfun.com/products/13699): to put multiple buttons on one input for each bar/rod/pole (Did we come up with a taxonomy for this :smile:)
  - [ ] 8x 4+ pin connectors (to transfer data from button shift registers to controller)
    - [RJ45](https://www.sparkfun.com/products/643)/[RJ11](https://www.sparkfun.com/products/132)?
    - [TRRS](https://www.sparkfun.com/products/12639)?
    - [USB](https://www.sparkfun.com/products/587)?
## Misc.
- [ ] [Protoboard](https://www.sparkfun.com/products/13268) to solder/mount components
- [ ] Solder
- [ ] Wire
## Mounting
- [ ] Enclosure for each button strip
  - One for each bar. Something beefy to stand up to excited scoring (wood, aluminum channel?)
- [ ] Mounting that won't damage side of table, e.g. Command Strips

**Comment by twkm** [comment]
I'm leaning towards using RJ45 (Ethernet) connectors to link each rod of buttons to the controller, since we can make them easily ourselves to any length. Any thoughts?

**Comment by seanrabey** [comment]
I think that would be great. Would and Ethernet connectors have enough lines to handle all of the buttons on the 5 bar? I'm trying to imagine how it would get wired up

**Comment by twkm** [comment]
RJ45 has 8 transmission lines, and we'd need 4 to communicate with one shift register. One shift register can give us 8 inputs/outputs (depending on the shift register) using 4 I/O pins on the teensy.

"An 8 bit shift register needs 4 lines of a microcontroller. One for the Clock to time the data transfer, one to the enable the clock, one for loading/latching/shifting the bits, and one for the serial data transfer." https://learn.sparkfun.com/tutorials/shift-registers

So 1 shift register per bar controller can listen to up to 8 buttons. That leaves us with another 4 pins on the ethernet to drive another SR for LED or RGB LED output (or whatever) at a later date.

I think 8 _should_ be more than enough. Until we think of the next crazy thing :smile: 

Further reading: 

https://en.wikipedia.org/wiki/Shift_register
